tabs:
    fields:
### Content
        business_card_section:
            label: 'Business card'
            type: section
            span: full
            tab: 'Content'
        business_card_name:
            label: 'Store name'
            type: text
            span: left
            tab: 'Content'
        business_card_image:
            label: 'Logo'
            comment: 'Recommended resolution: 300×75px. The SVG format is supported.'
            type: mediafinder
            span: right
            mode: image
            tab: 'Content'
        business_card_description:
            label: 'Store description or tagline'
            type: text
            span: left
            tab: 'Content'
        business_card_image_alt:
            label: 'Alternative text'
            comment: 'This string will have been shown in case an image has not loaded on the page.'
            type: text
            span: right
            tab: 'Content'
        business_card_phone:
            label: 'Phone'
            comment: 'This string will be rendered on the page as a clickable hyperlink.'
            type: text
            span: left
            tab: 'Content'
        business_card_image_title:
            label: 'Title'
            comment: 'This string will be shown on the mouse hover on the image.'
            type: text
            span: right
            tab: 'Content'
        business_card_email:
            label: 'E-mail'
            comment: 'This string will be rendered on the page as a clickable hyperlink.'
            type: text
            span: left
            tab: 'Content'
        business_card_address:
            label: 'Address'
            type: text
            span: full
            tab: 'Content'
        business_card_copyright:
            label: 'Page copyright'
            placeholder: '© 2020 Atmosphere. All rights reserved.'
            type: text
            span: full
            tab: 'Content'

        top_info_block_section:
            label: 'Top Info Block'
            type: section
            span: full
            tab: 'Content'
        top_info_block_active:
            label: 'lovata.toolbox::lang.field.active'
            type: switch
            span: full
            tab: 'Content'
        top_info_block:
            label: 'lovata.toolbox::lang.field.description'
            type: richeditor
            span: full
            tab: 'Content'
### Functionality
        shopaholic_bar_section:
            label: 'Powered by Shopaholic bar'
            type: section
            span: full
            tab: 'Functionality'
        shopaholic_bar:
            label: 'Active'
            type: switch
            defaul: on
            span: full
            tab: 'Functionality'
